# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='title',
            field=models.CharField(max_length=32, verbose_name='班级名'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=256, verbose_name='选项名'),
        ),
        migrations.AlterField(
            model_name='quesrionnaire',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classlist', verbose_name='调查班级'),
        ),
        migrations.AlterField(
            model_name='quesrionnaire',
            name='title',
            field=models.CharField(max_length=128, verbose_name='问卷标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=128, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '评分'), (2, '单选'), (3, '评价')], verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classlist', verbose_name='所属班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
